var dados = {
	"login": "MeryUgoski",
	"id": 51347075,
	"node_id": "MDQ6VXNlcjUxMzQ3MDc1",
	"avatar_url": "https://avatars2.githubusercontent.com/u/51347075?v=4",
	"gravatar_id": "",
	"url": "https://api.github.com/users/MeryUgoski",
	"html_url": "https://github.com/MeryUgoski",
	"followers_url": "https://api.github.com/users/MeryUgoski/followers",
	"following_url": "https://api.github.com/users/MeryUgoski/following{/other_user}",
	"gists_url": "https://api.github.com/users/MeryUgoski/gists{/gist_id}",
	"starred_url": "https://api.github.com/users/MeryUgoski/starred{/owner}{/repo}",
	"subscriptions_url": "https://api.github.com/users/MeryUgoski/subscriptions",
	"organizations_url": "https://api.github.com/users/MeryUgoski/orgs",
	"repos_url": "https://api.github.com/users/MeryUgoski/repos",
	"events_url": "https://api.github.com/users/MeryUgoski/events{/privacy}",
	"received_events_url": "https://api.github.com/users/MeryUgoski/received_events",
	"type": "User",
	"site_admin": false,
	"name":"MeryUgoski",
	"company": null,	
	"blog": "",
	"location": null,
	"email": null,
	"hireable": null,
	"bio": "ola tudo bem",
	"public_repos": 7,
	"public_gists": 0,
	"followers": 3,
	"following": 1,
	"created_at": "2019-06-04T00:19:31Z",
	"updated_at": "2019-06-26T23:13:54Z"
}